# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Fauzi Ferdiansyah Profile Website
email: fetruzie2@gmail.com
description: "Fauzi Ferdiansyah's Landing Page"
keywords: "fauzi, fauzi ferdiansyah, uzi, dacil, dachiel, web developer, web designer, full-stack, programer, frontend, backend, profile, profile website, profil, profil pribadi, desain, ganteng, keren, kece, online shop, toko online, wordpress, laravel, cakephp, golang, ruby, site generator, designer, graphic design, desain grafis, material, web desain, desainer, kreatif, inovatif, produktif, indonesia"
baseurl: "/id" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: landingtheme
plugins:
  - jekyll-feed

# ADD ONS
name: Fauzi Ferdiansyah
as: Web Developer, Front-end, Graphic Designer and Writer.

# Social Media
fb: https://www.facebook.com/fauzi.ferdiansyah.5
ig: https://www.instagram.com/fauzi_ferdiansyahs/
tw: https://twitter.com/faferuziel
gh: https://github.com/fauziferdiansyah
li: https://www.linkedin.com/in/fauzi-ferdiansyah/
wa: https://api.whatsapp.com/send?phone=628989515744&text=Assalamualaikum%20Fauzi
# my_web: http://www.fauzi.asvicode.com
medium: https://medium.com/@fauzifrd
codepen: https://codepen.io/fauziferdiansyah
stackoverflow: https://stackoverflow.com/users/11276325/fauzi-ferdiansyah
twitter: https://twitter.com/den_dacil
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
